version: '3'

services:
  alchemist:
    build: 
      dockerfile: ./alchemist/Dockerfile
      context: ./
    ports:
      - 8080:8080
    volumes:
      - './alchemist:/code/'
    depends_on:
<<<<<<< HEAD
      - "redis"
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}
=======
      - redis
>>>>>>> 2bba826 (fix: backend complete implementation)
  redis:
    image: redis
    ports:
      - "6379:6379"
<<<<<<< HEAD
    volumes:
        - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "-h", "localhost", "-p", "6379", "ping"]
      interval: 2s
      timeout: 1m30s
      retries: 5
      start_period: 5s
  my-app:
    build:
      context: .
      dockerfile: ./ui/Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./ui/:/ui
  jupyter:
    image: jupyter/minimal-notebook:latest
    container_name: jupyter
    volumes:
      - ./:/home/jovyan/chatbot
    ports:
      - 8888:8888
    depends_on:
      - "redis"
    environment:
      JUPYTER_ENABLE_LAB: "yes"
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      
=======
>>>>>>> 2bba826 (fix: backend complete implementation)

volumes:
  redis_data: