version: '3'

services:
  alchemist:
    build: 
      dockerfile: ./alchemist/Dockerfile
      context: ./
    ports:
      - 8080:8080
    volumes:
      - './alchemist:/code/'
    depends_on:
      - redis
  redis:
    image: redis
    ports:
      - "6379:6379"

volumes:
  redis_data: